MOVIES = [
    (
        "Puss in Boots: The Last Wish",
        8.6,
        "https://image.tmdb.org/t/p/w300/1NqwE6LP9IEdOZ57NCT51ftHtWT.jpg",
        12066.07,
        "Animated Action Adventure",
        101,
        "Puss in Boots is on a mission to recover the Princess' stolen ruby from the notorious French thief, Whisperer. Reluctantly accompanied by three little kittens, Three Diablos, Puss must tame them before they endanger the mission.",
    ),
    (
        "Avatar The Way of Water",
        7.7,
        "https://image.tmdb.org/t/p/w300/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
        3948.296,
        "Action Adventure Fantasy",
        192,
        "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    ),
    (
        "Violent Night",
        7.7,
        "https://image.tmdb.org/t/p/w300/nhXjUvOvq7rJlvJFCrZMUUJ9Mn0.jpg",
        2625.132,
        "Action Thriller Comedy",
        111,
        "When a team of mercenaries breaks into a wealthy family compound on Christmas Eve, taking everyone inside hostage, the team isn’t prepared for a surprise combatant: Santa Claus is on the grounds, and he’s about to show why this Nick is no saint.",
    ),
    (
        "Glass Onion: A Knives Out Mystery",
        7.1,
        "https://image.tmdb.org/t/p/w300/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg",
        1906.416,
        "Mystery Crime Comedy",
        139,
        "World-famous detective Benoit Blanc heads to Greece to peel back the layers of a mystery surrounding a tech billionaire and his eclectic crew of friends.",
    ),
    (
        "M3GAN",
        7.1,
        "https://image.tmdb.org/t/p/w300/7CNCv9uhqdwK7Fv4bR4nmDysnd9.jpg",
        2607.511,
        "Horror Thriller Sci-Fi",
        101,
        "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
    ),
    (
        "Black Adam",
        7.2,
        "https://image.tmdb.org/t/p/w300/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
        2250.041,
        "Action Sci-Fi",
        125,
        "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
    ),
    (
        "Troll",
        6.7,
        "https://image.tmdb.org/t/p/w300/9z4jRr43JdtU66P0iy8h18OyLql.jpg",
        2300.001,
        "Action Adventure Fantasy",
        101,
        "Deep inside the mountain of Dovre, something gigantic awakens after being trapped for a thousand years. Destroying everything in its path, the creature is fast approaching the capital of Norway. But how do you stop something you thought only existed in Norwegian folklore?",
    ),
    (
        "Prey for the Devil",
        7.2,
        "https://image.tmdb.org/t/p/w300/w3s6XEDNVGq5LUlghqs6VlvsvL6.jpg",
        1623.652,
        "Horror Thriller",
        93,
        "In response to a global rise in demonic possessions, the Catholic Church reopens exorcism schools to train priests in the Rite of Exorcism. On this spiritual battlefield, an unlikely warrior rises: a young nun, Sister Ann. Thrust onto the spiritual frontline with fellow student Father Dante, Sister Ann finds herself in a battle for the soul of a young girl and soon realizes the Devil has her right where he wants her.",
    ),
    (
        "Black Panther: Wakanda Forever",
        7.5,
        "https://image.tmdb.org/t/p/w300/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
        1528.32,
        "Action Adventure Sci-Fi",
        161,
        "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
    ),
    (
        "The Boss Baby: Christmas Bonus",
        6.7,
        "https://image.tmdb.org/t/p/w300/iMmMxF6f2OonUrXrHKBLSYAhXly.jpg",
        795.939,
        "Animated Comedy Family",
        45,
        "Christmas Eve takes a twisty turn when the Boss Baby accidentally swaps places with one of Santa's elves and gets stranded at the North Pole.",
    ),
    (
        "The Minute You Wake Up Dead",
        5.6,
        "https://image.tmdb.org/t/p/w300/pUPwTbnAqfm95BZjNBnMMf39ChT.jpg",
        641.645,
        "Thriller",
        90,
        "A stockbroker in a small southern town gets embroiled in an insurance scam with a next-door neighbor that leads to multiple murders when a host of other people want in on the plot. Sheriff Thurmond Fowler, the by-the-book town sheriff for over four decades, works earnestly to try and unravel the town’s mystery and winds up getting more than he bargained for.",
    ),
    (
        "Top Gun: Maverick",
        8.3,
        "https://image.tmdb.org/t/p/w300/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
        653.607,
        "Action Drama",
        131,
        "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
    ),
    (
        "Spider-Man: No Way Home",
        8,
        "https://image.tmdb.org/t/p/w300/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg",
        524.864,
        "Action Adventure Sci-Fi",
        148,
        "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    ),
    (
        "Thor: Love and Thunder",
        6.7,
        "https://image.tmdb.org/t/p/w300/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
        409.118,
        "Action Adventure Fantasy",
        125,
        "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
    ),
    (
        "The Incredible Hulk",
        6.2,
        "https://image.tmdb.org/t/p/w300/gKzYx79y0AQTL4UAk1cBQJ3nvrm.jpg",
        59.269,
        "Action Thriller Sci-Fi",
        112,
        "Scientist Bruce Banner scours the planet for an antidote to the unbridled force of rage within him: the Hulk. But when the military masterminds who dream of exploiting his powers force him back to civilization, he finds himself coming face to face with a new, deadly foe.",
    ),
    (
        "Orphan: First Kill",
        6.8,
        "https://image.tmdb.org/t/p/w300/pHkKbIRoCe7zIFvqan9LFSaQAde.jpg",
        441.875,
        "Crime Drama Horror",
        99,
        "After escaping from an Estonian psychiatric facility, Leena Klammer travels to America by impersonating Esther, the missing daughter of a wealthy family. But when her mask starts to slip, she is put against a mother who will protect her family from the murderous “child” at any cost.",
    ),
    (
        "The Guardians of the Galaxy: Holiday Special",
        7.4,
        "https://image.tmdb.org/t/p/w300/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
        347.423,
        "Action Adventure Comedy",
        42,
        "On a mission to make Christmas unforgettable for Quill, the Guardians head to Earth in search of the perfect present.",
    ),
    (
        "Doctor Strange in the Multiverse of Madness",
        7.4,
        "https://image.tmdb.org/t/p/w300/fwBl3J2aEXru6mrr9Xg8O99Iz2K.jpg",
        369.635,
        "Action Fantasy Horror",
        127,
        "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
    ),
    (
        "Enola Holmes 2",
        7.7,
        "https://image.tmdb.org/t/p/w300/tegBpjM5ODoYoM1NjaiHVLEA0QM.jpg",
        292.598,
        "Drama Crime Mysterious",
        129,
        "Now a detective-for-hire like her infamous brother, Enola Holmes takes on her first official case to find a missing girl, as the sparks of a dangerous conspiracy ignite a mystery that requires the help of friends — and Sherlock himself — to unravel.",
    ),
    (
        "The Batman",
        7.7,
        "https://image.tmdb.org/t/p/w300/74xTEgt7R36Fpooo50r9T25onhq.jpg",
        359.665,
        "Action Crime Mystery",
        176,
        "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
    ),
    (
        "DC League of Super-Pets",
        7.4,
        "https://image.tmdb.org/t/p/w300/r7XifzvtezNt31ypvsmb6Oqxw49.jpg",
        277.103,
        "Animated Family Adventure",
        106,
        "When Superman and the rest of the Justice League are kidnapped, Krypto the Super-Dog must convince a rag-tag shelter pack - Ace the hound, PB the potbellied pig, Merton the turtle and Chip the squirrel - to master their own newfound powers and help him rescue the superheroes.",
    ),
    (
        "The Shawshank Redemption",
        8.7,
        "https://image.tmdb.org/t/p/w300/hBcY0fE9pfXzvVaY4GKarweriG2.jpg",
        94.813,
        "Drama Crime",
        142,
        "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    ),
    (
        "Harry Potter and the Philosopher's Stone",
        7.9,
        "https://image.tmdb.org/t/p/w300/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
        221.393,
        "Fantasy Family Mystery",
        152,
        "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths—and about the villain who's to blame.",
    ),
    (
        "Harry Potter and the Half-Blood Prince",
        7.7,
        "https://image.tmdb.org/t/p/w300/z7uo9zmQdQwU5ZJHFpv2Upl30i1.jpg",
        202.236,
        "Fantasy Family Mystery",
        147,
        "As Lord Voldemort tightens his grip on both the Muggle and wizarding worlds, Hogwarts is no longer a safe haven. Harry suspects perils may even lie within the castle, but Dumbledore is more intent upon preparing him for the final battle fast approaching. Together they work to find the key to unlock Voldemorts defenses and to this end, Dumbledore recruits his old friend and colleague Horace Slughorn, whom he believes holds crucial information. Even as the decisive showdown looms, romance blossoms for Harry, Ron, Hermione and their classmates. Love is in the air, but danger lies ahead and Hogwarts may never be the same again.",
    ),
    (
        "Harry Potter and the Goblet of Fire",
        7.8,
        "https://image.tmdb.org/t/p/w300/fECBtHlr0RB3foNHDiCBXeg9Bv9.jpg",
        179.886,
        "Fantasy Family Mystery",
        157,
        "When Harry Potter's name emerges from the Goblet of Fire, he becomes a competitor in a grueling battle for glory among three wizarding schools—the Triwizard Tournament. But since Harry never submitted his name for the Tournament, who did? Now Harry must confront a deadly dragon, fierce water demons and an enchanted maze only to find himself in the cruel grasp of He Who Must Not Be Named.",
    ),
    (
        "Harry Potter and the Chamber of Secrets",
        7.7,
        "https://image.tmdb.org/t/p/w300/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg",
        193.002,
        "Fantasy Family Mystery",
        161,
        "Cars fly, trees fight back, and a mysterious house-elf comes to warn Harry Potter at the start of his second year at Hogwarts. Adventure and danger await when bloody writing on a wall announces: The Chamber Of Secrets Has Been Opened. To save Hogwarts will require all of Harry, Ron and Hermione’s magical abilities and courage.",
    ),
    (
        "Harry Potter and the Deathly Hallows: Part 2",
        8.1,
        "https://image.tmdb.org/t/p/w300/c54HpQmuwXjHq2C9wmoACjxoom3.jpg",
        173.78,
        "Fantasy Family Mystery",
        125,
        "Harry, Ron and Hermione continue their quest to vanquish the evil Voldemort once and for all. Just as things begin to look hopeless for the young wizards, Harry discovers a trio of magical objects that endow him with powers to rival Voldemort's formidable skills.",
    ),
    (
        "Harry Potter and the Prisoner of Azkaban",
        8,
        "https://image.tmdb.org/t/p/w300/aWxwnYoe8p2d2fcxOqtvAtJ72Rw.jpg",
        172.933,
        "Fantasy Family Mystery",
        141,
        "Year three at Hogwarts means new fun and challenges as Harry learns the delicate art of approaching a Hippogriff, transforming shape-shifting Boggarts into hilarity and even turning back time. But the term also brings danger: soul-sucking Dementors hover over the school, an ally of the accursed He-Who-Cannot-Be-Named lurks within the castle walls, and fearsome wizard Sirius Black escapes Azkaban. And Harry will confront them all.",
    ),
    (
        "Harry Potter and the Deathly Hallows: Part 1",
        7.8,
        "https://image.tmdb.org/t/p/w300/iGoXIpQb7Pot00EEdwpwPajheZ5.jpg",
        163.419,
        "Fantasy Family Mystery",
        140,
        "Harry, Ron and Hermione walk away from their last year at Hogwarts to find and destroy the remaining Horcruxes, putting an end to Voldemort's bid for immortality. But with Harry's beloved Dumbledore dead and Voldemort's unscrupulous Death Eaters on the loose, the world is more dangerous than ever.",
    ),
    (
        "Harry Potter and the Order of the Phoenix",
        7.7,
        "https://image.tmdb.org/t/p/w300/5aOyriWkPec0zUDxmHFP9qMmBaj.jpg",
        166.205,
        "Fantasy Family Mystery",
        138,
        "Returning for his fifth year of study at Hogwarts, Harry is stunned to find that his warnings about the return of Lord Voldemort have been ignored. Left with no choice, Harry takes matters into his own hands, training a small group of students to defend themselves against the dark arts.",
    ),
    (
        "Harry Potter 20th Anniversary: Return to Hogwarts",
        7.3,
        "https://image.tmdb.org/t/p/w300/jntLBq0MLR3hrwKaTQswxACRPMs.jpg",
        89.724,
        "Documentary",
        98,
        "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
    ),
    (
        "Avengers: Endgame",
        8.3,
        "https://image.tmdb.org/t/p/w300/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
        148.102,
        "Action Adventure Sci-Fi",
        182,
        "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    ),
    (
        "Avengers: Infinity War",
        8.3,
        "https://image.tmdb.org/t/p/w300/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
        230.737,
        "Action Adventure Sci-Fi",
        149,
        "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
    ),
    (
        "The Avengers",
        7.7,
        "https://image.tmdb.org/t/p/w300/tYqp6vEOo8YlVWrYQvt9nyOhsA2.jpg",
        152.893,
        "Action Adventure Sci-Fi",
        143,
        "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!",
    ),
    (
        "Avengers: Age of Ultron",
        7.3,
        "https://image.tmdb.org/t/p/w300/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg",
        126.36,
        "Action Adventure Sci-Fi",
        141,
        "When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.",
    ),
    (
        "The Lord of the Rings: The Two Towers",
        8.4,
        "https://image.tmdb.org/t/p/w300/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
        85.927,
        "Fantasy Adventure Action",
        172,
        "Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.",
    ),
    (
        "The Lord of the Rings: The Fellowship of the Ring",
        8.4,
        "https://image.tmdb.org/t/p/w300/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
        111.916,
        "Fantasy Adventure Action",
        172,
        "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
    ),
    (
        "The Lord of the Rings: The Return of the King",
        8.5,
        "https://image.tmdb.org/t/p/w300/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
        90.204,
        "Fantasy Adventure Action",
        201,
        "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
    ),
    (
        "Batman Begins",
        7.7,
        "https://image.tmdb.org/t/p/w300/8RW2runSEc34IwKN2D1aPcJd2UL.jpg",
        60.378,
        "Action Adventure",
        140,
        "Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.",
    ),
    (
        "Batman v Superman: Dawn of Justice",
        5.9,
        "https://image.tmdb.org/t/p/w300/5UsK3grJvtQrtzEgqNlDljJW96w.jpg",
        84.615,
        "Sci-Fi Adventure Action",
        151,
        "Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.",
    ),
    (
        "Man of Steel",
        6.6,
        "https://image.tmdb.org/t/p/w300/j3BrQDIKThJU46vVNMCFUGZIEyW.jpg",
        74.836,
        "Action Adventure Fantasy",
        143,
        "A young boy learns that he has extraordinary powers and is not of this earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind.",
    ),
    (
        "The Pianist",
        8.4,
        "https://image.tmdb.org/t/p/w300/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
        37.701,
        "Biographical War Musical",
        150,
        "The true story of pianist Władysław Szpilman's experiences in Warsaw during the Nazi occupation. When the Jews of the city find themselves forced into a ghetto, Szpilman finds work playing in a café; and when his family is deported in 1942, he stays behind, works for a while as a laborer, and eventually goes into hiding in the ruins of the war-torn city.",
    ),
    (
        "Schindler's List",
        8.6,
        "https://image.tmdb.org/t/p/w300/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
        60.267,
        "Drama Historical Biographical",
        195,
        "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    ),
    (
        "Abandoned",
        6.4,
        "https://image.tmdb.org/t/p/w300/9im8JhelZGDbDpXTigJbjMQqy3S.jpg",
        689.873,
        "Horror",
        102,
        "After a young couple moves into a remote farmhouse with their infant son, the woman's struggles with postpartum psychosis begin to intensify... as the house reveals secrets of its own.",
    ),
    (
        "The Godfather",
        8.7,
        "https://image.tmdb.org/t/p/w300/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        120.809,
        "Drama Crime",
        175,
        "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    ),
    (
        "The Godfather Part II",
        8.6,
        "https://image.tmdb.org/t/p/w300/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
        73.078,
        "Drama Crime",
        202,
        "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    ),
    (
        "The Godfather Part III",
        7.4,
        "https://image.tmdb.org/t/p/w300/lm3pQ2QoQ16pextRsmnUbG2onES.jpg",
        93.192,
        "Drama Crime",
        162,
        "In the midst of trying to legitimize his business dealings in 1979 New York and Italy, aging mafia don, Michael Corleone seeks forgiveness for his sins while taking a young protege under his wing.",
    ),
    (
        "Spider-Man",
        7.3,
        "https://image.tmdb.org/t/p/w300/gh4cZbhZxyTbgxQPxD0dOudNPTn.jpg",
        107.152,
        "Action Adventure Fantasy",
        121,
        "After being bitten by a genetically altered spider at Oscorp, nerdy but endearing high school student Peter Parker is endowed with amazing powers to become the superhero known as Spider-Man.",
    ),
    (
        "Spider-Man 2",
        7.2,
        "https://image.tmdb.org/t/p/w300/olxpyq9kJAZ2NU1siLshhhXEPR7.jpg",
        36.043,
        "Action Adventure Fantasy",
        127,
        "Peter Parker is going through a major identity crisis. Burned out from being Spider-Man, he decides to shelve his superhero alter ego, which leaves the city suffering in the wake of carnage left by the evil Doc Ock. In the meantime, Parker still can't act on his feelings for Mary Jane Watson, a girl he's loved since childhood. A certain anger begins to brew in his best friend Harry Osborn as well...",
    ),
    (
        "Spider-Man 3",
        6.4,
        "https://image.tmdb.org/t/p/w300/rmGLCH63IBByBx5SCbsn0pNWHdg.jpg",
        89.605,
        "Action Adventure Fantasy",
        139,
        "The seemingly invincible Spider-Man goes up against an all-new crop of villains—including the shape-shifting Sandman. While Spider-Man’s superpowers are altered by an alien organism, his alter ego, Peter Parker, deals with nemesis Eddie Brock and also gets caught up in a love triangle.",
    ),
    (
        "The Amazing Spider-Man",
        6.7,
        "https://image.tmdb.org/t/p/w300/fSbqPbqXa7ePo8bcnZYN9AHv6zA.jpg",
        106.938,
        "Action Adventure Fantasy",
        131,
        "Peter Parker is an outcast high schooler abandoned by his parents as a boy, leaving him to be raised by his Uncle Ben and Aunt May. Like most teenagers, Peter is trying to figure out who he is and how he got to be the person he is today. As Peter discovers a mysterious briefcase that belonged to his father, he begins a quest to understand his parents' disappearance – leading him directly to Oscorp and the lab of Dr. Curt Connors, his father's former partner. As Spider-Man is set on a collision course with Connors' alter ego, The Lizard, Peter will make life-altering choices to use his powers and shape his destiny to become a hero.",
    ),
    (
        "The Amazing Spider-Man 2",
        6.5,
        "https://image.tmdb.org/t/p/w300/c3e9e18SSlvFd1cQaGmUj5tqL5P.jpg",
        100.492,
        "Action Adventure Fantasy",
        142,
        "For Peter Parker, life is busy. Between taking out the bad guys as Spider-Man and spending time with the person he loves, Gwen Stacy, high school graduation cannot come quickly enough. Peter has not forgotten about the promise he made to Gwen’s father to protect her by staying away, but that is a promise he cannot keep. Things will change for Peter when a new villain, Electro, emerges, an old friend, Harry Osborn, returns, and Peter uncovers new clues about his past.",
    ),
    (
        "Spider-Man: Into the Spider-Verse",
        8.4,
        "https://image.tmdb.org/t/p/w300/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
        120.05,
        "Animated Action Sci-Fi",
        117,
        'Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson "Kingpin" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.',
    ),
    (
        "Spider-Man: Homecoming",
        7.4,
        "https://image.tmdb.org/t/p/w300/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
        122.318,
        "Action Adventure Sci-Fi",
        133,
        "Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges",
    ),
    (
        "Spider-Man: Far from Home",
        7.5,
        "https://image.tmdb.org/t/p/w300/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
        92.318,
        "Action Adventure Sci-Fi",
        130,
        "Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.",
    ),
    (
        "Thor: Ragnarok",
        7.6,
        "https://image.tmdb.org/t/p/w300/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
        86.369,
        "Action Adventure Fantasy",
        130,
        "Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his home-world and the end of Asgardian civilization, at the hands of a powerful new threat, the ruthless Hela.",
    ),
    (
        "Smile",
        6.8,
        "https://image.tmdb.org/t/p/w300/aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg",
        713.316,
        "Horror",
        117,
        "After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can't explain. As an overwhelming terror begins taking over her life, Rose must confront her troubling past in order to survive and escape her horrifying new reality.",
    ),
    (
        "Pokémon Detective Pikachu",
        7,
        "https://image.tmdb.org/t/p/w300/wgQ7APnFpf1TuviKHXeEe3KnsTV.jpg",
        62.654,
        "Action Family Mystery",
        104,
        "In a world where people collect pocket-size monsters (Pokémon) to do battle, a boy comes across an intelligent monster who seeks to be a detective.",
    ),
    (
        "The Enforcer",
        6.9,
        "https://image.tmdb.org/t/p/w300/72V1r1G8S87ELagVxjqAUdChMCt.jpg",
        2329.449,
        "Action Thriller",
        90,
        "A noir thriller set in Miami, the film follows an enforcer who discovers his femme fatale boss has branched out into cyber sex trafficking, putting a young runaway he’s befriended at risk. He sacrifices everything to save the young girl from the deadly organization he’s spent his life building.",
    ),
    (
        "Devotion",
        7.1,
        "https://image.tmdb.org/t/p/w300/26yQPXymbWeCLKwcmyL8dRjAzth.jpg",
        2344.009,
        "Action Drama War",
        138,
        "The harrowing true story of two elite US Navy fighter pilots during the Korean War. Their heroic sacrifices would ultimately make them the Navy's most celebrated wingmen.",
    ),
    (
        "The Last Client",
        7.4,
        "https://image.tmdb.org/t/p/w300/oUhZzMpHAMgdRgLbsvBIqhY7fKe.jpg",
        1261.87,
        "Horror Thriller Drama",
        93,
        "Renowned psychologist Susanne (Signe Egholm Olsen) is caught in a living nightmare when her new client (Anton Hjejle) turns out to be a wanted serial killer.",
    ),
    (
        "Captain Marvel",
        6.9,
        "https://image.tmdb.org/t/p/w300/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
        60.56,
        "Action Adventure Sci-Fi",
        124,
        "The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.",
    ),
    (
        "Thor",
        6.8,
        "https://image.tmdb.org/t/p/w300/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg",
        79.81,
        "Action Adventure Fantasy",
        110,
        "Against his father Odin's will, The Mighty Thor - a powerful but arrogant warrior god - recklessly reignites an ancient war. Thor is cast down to Earth and forced to live among humans as punishment. Once here, Thor learns what it takes to be a true hero when the most dangerous villain of his world sends the darkest forces of Asgard to invade Earth.",
    ),
    (
        "All Quiet on the Western Front",
        7.8,
        "https://image.tmdb.org/t/p/w300/hYqOjJ7Gh1fbqXrxlIao1g8ZehF.jpg",
        21.689,
        "War Action Drama",
        148,
        "Paul Baumer and his friends Albert and Muller, egged on by romantic dreams of heroism, voluntarily enlist in the German army. Full of excitement and patriotic fervour, the boys enthusiastically march into a war they believe in. But once on the Western Front, they discover the soul-destroying horror of World War I.",
    ),
    (
        "Spiral: From the Book of Saw",
        6.1,
        "https://image.tmdb.org/t/p/w300/qkl6mRoFexK2FGWCbAsvrRxjWaF.jpg",
        51.467,
        "Horror Crime Mysterious",
        93,
        "Working in the shadow of an esteemed police veteran, brash Detective Ezekiel “Zeke” Banks and his rookie partner take charge of a grisly investigation into murders that are eerily reminiscent of the city’s gruesome past.  Unwittingly entrapped in a deepening mystery, Zeke finds himself at the center of the killer’s morbid game.",
    ),
    (
        "Doctor Strange",
        7.4,
        "https://image.tmdb.org/t/p/w300/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
        71.597,
        "Action Adventure Fantasy",
        115,
        "After his career is destroyed, a brilliant but arrogant surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.",
    ),
    (
        "Fantastic Beasts and Where to Find Them",
        7.3,
        "https://image.tmdb.org/t/p/w300/h6NYfVUyM6CDURtZSnBpz647Ldd.jpg",
        71.382,
        "Adventure Family Fantasy",
        133,
        "In 1926, Newt Scamander arrives at the Magical Congress of the United States of America with a magically expanded briefcase, which houses a number of dangerous creatures and their habitats. When the creatures escape from the briefcase, it sends the American wizarding authorities after Newt, and threatens to strain even further the state of magical and non-magical relations.",
    ),
    (
        "Fantastic Beasts: The Crimes of Grindelwald",
        6.9,
        "https://image.tmdb.org/t/p/w300/fMMrl8fD9gRCFJvsx0SuFwkEOop.jpg",
        39.89,
        "Adventure Family Fantasy",
        134,
        "Gellert Grindelwald has escaped imprisonment and has begun gathering followers to his cause—elevating wizards above all non-magical beings. The only one capable of putting a stop to him is the wizard he once called his closest friend, Albus Dumbledore. However, Dumbledore will need to seek help from the wizard who had thwarted Grindelwald once before, his former student Newt Scamander, who agrees to help, unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world.",
    ),
    (
        "Fantastic Beasts: The Secrets of Dumbledore",
        6.8,
        "https://image.tmdb.org/t/p/w300/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg",
        177.201,
        "Adventure Family Fantasy",
        143,
        "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.",
    ),
    (
        "Kingsman: The Secret Service",
        7.6,
        "https://image.tmdb.org/t/p/w300/ay7xwXn1G9fzX9TUBlkGA584rGi.jpg",
        61.14,
        "Action Adventure Thriller",
        129,
        "The story of a super-secret spy organization that recruits an unrefined but promising street kid into the agency's ultra-competitive training program just as a global threat emerges from a twisted tech genius.",
    ),
    (
        "Kingsman: The Golden Circle",
        7,
        "https://image.tmdb.org/t/p/w300/34xBL6BXNYFqtHO9zhcgoakS4aP.jpg",
        55.416,
        "Action Adventure Comedy",
        141,
        "When an attack on the Kingsman headquarters takes place and a new villain rises, Eggsy and Merlin are forced to work together with the American agency known as the Statesman to save the world.",
    ),
    (
        "Morbius",
        6.2,
        "https://image.tmdb.org/t/p/w300/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg",
        175.369,
        "Action Horror Sci-Fi",
        105,
        "Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.",
    ),
    (
        "Uncharted",
        7.1,
        "https://image.tmdb.org/t/p/w300/rJHC1RUORuUhtfNb4Npclx0xnOf.jpg",
        233.496,
        "Action Adventure",
        117,
        "A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.",
    ),
    (
        "Annabelle",
        5.7,
        "https://image.tmdb.org/t/p/w300/a9iL3FIwLrympRyiL5v0tAkwrvX.jpg",
        45.523,
        "Horror Mysterious Thriller",
        95,
        "A couple begins to experience terrifying supernatural occurrences involving a vintage doll shortly after their home is invaded by satanic cultists.",
    ),
    (
        "Annabelle: Creation",
        6.6,
        "https://image.tmdb.org/t/p/w300/tb86j8jVCVsdZnzf8I6cIi65IeM.jpg",
        62.097,
        "Horror Mysterious Thriller",
        109,
        "Several years after the tragic death of their little girl, a doll maker and his wife welcome a nun and several girls from a shuttered orphanage into their home, soon becoming the target of the doll maker's possessed creation—Annabelle.",
    ),
    (
        "Annabelle Comes Home",
        6.4,
        "https://image.tmdb.org/t/p/w300/znpnoIhwBtgOwFll9Q759hrYAfG.jpg",
        68.147,
        "Horror Mysterious Thriller",
        106,
        "Determined to keep Annabelle from wreaking more havoc, demonologists Ed and Lorraine Warren bring the possessed doll to the locked artifacts room in their home, placing her “safely” behind sacred glass and enlisting a priest’s holy blessing. But an unholy night of horror awaits as Annabelle awakens the evil spirits in the room, who all set their sights on a new target—the Warrens' ten-year-old daughter, Judy, and her friends.",
    ),
    (
        "Venom",
        6.8,
        "https://image.tmdb.org/t/p/w300/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
        65.551,
        "Action Sci-Fi Thriller",
        112,
        "Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of Venom, a violent, super powerful alien symbiote. Soon, he must rely on his newfound powers to protect the world from a shadowy organization looking for a symbiote of their own.",
    ),
    (
        "Dune",
        7.8,
        "https://image.tmdb.org/t/p/w300/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
        108.445,
        "Sci-Fi Action Adventure",
        155,
        "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    ),
    (
        "Tenet",
        7.2,
        "https://image.tmdb.org/t/p/w300/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
        65.414,
        "Action Drama Sci-Fi",
        150,
        "Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
    ),
    (
        "Joker",
        8.2,
        "https://image.tmdb.org/t/p/w300/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
        87.173,
        "Crime Drama Thriller",
        122,
        "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
    ),
    (
        "It",
        7.2,
        "https://image.tmdb.org/t/p/w300/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg",
        65.541,
        "Drama Horror Thriller",
        135,
        "In a small town in Maine, seven children known as The Losers Club come face to face with life problems, bullies and a monster that takes the shape of a clown called Pennywise.",
    ),
    (
        "It Chapter Two",
        6.9,
        "https://image.tmdb.org/t/p/w300/zfE0R94v1E8cuKAerbskfD3VfUt.jpg",
        92.239,
        "Horror Thriller Drama",
        165,
        "27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers' Club, who have grown up and moved away from Derry, are brought back together by a devastating phone call.",
    ),
    (
        "John Wick",
        7.4,
        "https://image.tmdb.org/t/p/w300/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
        87.654,
        "Action Crime Thriller",
        101,
        "Ex-hitman John Wick comes out of retirement to track down the gangsters that took everything from him.",
    ),
    (
        "John Wick: Chapter 2",
        7.3,
        "https://image.tmdb.org/t/p/w300/kL99FVq572hNPfMyfQCT7tGFNeQ.jpg",
        133.026,
        "Action Crime Thriller",
        122,
        "John Wick is forced out of retirement by a former associate looking to seize control of a shadowy international assassins’ guild. Bound by a blood oath to aid him, Wick travels to Rome and does battle against some of the world’s most dangerous killers.",
    ),
    (
        "John Wick: Chapter 3 - Parabellum",
        7.4,
        "https://image.tmdb.org/t/p/w300/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg",
        127.359,
        "Action Crime Thriller",
        131,
        "Super-assassin John Wick returns with a $14 million price tag on his head and an army of bounty-hunting killers on his trail. After killing a member of the shadowy international assassin’s guild, the High Table, John Wick is excommunicado, but the world’s most ruthless hit men and women await his every turn.",
    ),
    (
        "Jigsaw",
        6.2,
        "https://image.tmdb.org/t/p/w300/2mUqHJG7ZiGwZYIylczFCsRPbXM.jpg",
        39.383,
        "Horror Crime Mysterious",
        91,
        "Dead bodies begin to turn up all over the city, each meeting their demise in a variety of grisly ways. All investigations begin to point the finger at deceased killer John Kramer.",
    ),
    (
        "The Nun",
        5.8,
        "https://image.tmdb.org/t/p/w300/sFC1ElvoKGdHJIWRpNB3xWJ9lJA.jpg",
        86.682,
        "Horror Mysterious Thriller",
        96,
        "When a young nun at a cloistered abbey in Romania takes her own life, a priest with a haunted past and a novitiate on the threshold of her final vows are sent by the Vatican to investigate. Together they uncover the order’s unholy secret. Risking not only their lives but their faith and their very souls, they confront a malevolent force in the form of the same demonic nun that first terrorized audiences in “The Conjuring 2” as the abbey becomes a horrific battleground between the living and the damned.",
    ),
    (
        "Deadpool",
        7.6,
        "https://image.tmdb.org/t/p/w300/fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg",
        98.082,
        "Action Comedy Adventure",
        108,
        "The origin story of former Special Forces operative turned mercenary Wade Wilson, who, after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
    ),
    (
        "Deadpool 2",
        7.5,
        "https://image.tmdb.org/t/p/w300/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
        79.995,
        "Action Comedy Adventure",
        119,
        "Wisecracking mercenary Deadpool battles the evil and powerful Cable and other bad guys to save a boy's life.",
    ),
    (
        "Ready Player One",
        7.6,
        "https://image.tmdb.org/t/p/w300/pU1ULUq8D3iRxl1fdX2lZIzdHuI.jpg",
        84.548,
        "Action Sci-Fi Adventure",
        140,
        "When the creator of a popular video game system dies, a virtual contest is created to compete for his fortune.",
    ),
    (
        "Warcraft",
        6.4,
        "https://image.tmdb.org/t/p/w300/nZIIOs06YigBnvmlJ2hxZeA8eTO.jpg",
        39.46,
        "Fantasy Adventure Action",
        123,
        "The peaceful realm of Azeroth stands on the brink of war as its civilization faces a fearsome race of invaders: orc warriors fleeing their dying home to colonize another. As a portal opens to connect the two worlds, one army faces destruction and the other faces extinction. From opposing sides, two heroes are set on a collision course that will decide the fate of their family, their people, and their home.",
    ),
    (
        "Minions: The Rise of Gru",
        7.5,
        "https://image.tmdb.org/t/p/w300/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
        296.794,
        "Animated Adventure Family",
        88,
        "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.",
    ),
    (
        "Hotel Transylvania: Transformania",
        7.1,
        "https://image.tmdb.org/t/p/w300/teCy1egGQa0y8ULJvlrDHQKnxBL.jpg",
        219.59,
        "Animated Fantasy Family",
        98,
        "When Van Helsing's mysterious invention, the \"Monsterfication Ray,\" goes haywire, Drac and his monster pals are all transformed into humans, and Johnny becomes a monster. In their new mismatched bodies, Drac and Johnny must team up and race across the globe to find a cure before it's too late, and before they drive each other crazy.",
    ),
    (
        "Shrek",
        7.7,
        "https://image.tmdb.org/t/p/w300/o04jZs5SXhbvhqO4981W7KJXOWZ.jpg",
        249.772,
        "Animated Adventure Family",
        90,
        "It ain't easy bein' green -- especially if you're a likable (albeit smelly) ogre named Shrek. On a mission to retrieve a gorgeous princess from the clutches of a fire-breathing dragon, Shrek teams up with an unlikely compatriot -- a wisecracking donkey.",
    ),
    (
        "Shrek 2",
        7.2,
        "https://image.tmdb.org/t/p/w300/2yYP0PQjG8zVqturh1BAqu2Tixl.jpg",
        215.945,
        "Animated Adventure Family",
        93,
        "Shrek, Fiona and Donkey set off to Far, Far Away to meet Fiona's mother and father. But not everyone is happy. Shrek and the King find it hard to get along, and there's tension in the marriage. The fairy godmother discovers that Shrek has married Fiona instead of her Son Prince Charming and sets about destroying their marriage.",
    ),
    (
        "Shrek the Third",
        6.3,
        "https://image.tmdb.org/t/p/w300/1V5pspgnFCXXWd9DddHBVIF2275.jpg",
        144.953,
        "Animated Adventure Family",
        93,
        "The King of Far Far Away has died and Shrek and Fiona are to become King & Queen. However, Shrek wants to return to his cozy swamp and live in peace and quiet, so when he finds out there is another heir to the throne, they set off to bring him back to rule the kingdom.",
    ),
    (
        "Interstellar",
        8.4,
        "https://image.tmdb.org/t/p/w300/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        172.883,
        "Sci-Fi Adventure Drama",
        169,
        "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    ),
    (
        "Guardians of the Galaxy",
        7.9,
        "https://image.tmdb.org/t/p/w300/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
        39.872,
        "Sci-Fi Adventure Fantasy",
        116,
        "Light years from Earth, 26 years after being abducted, Peter Quill finds himself the prime target of a manhunt after discovering an orb wanted by Ronan the Accuser.",
    ),
    (
        "Guardians of the Galaxy Vol. 2",
        7.6,
        "https://image.tmdb.org/t/p/w300/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg",
        71.276,
        "Sci-Fi Adventure Fantasy",
        136,
        "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
    ),
    (
        "Captain America: The Winter Soldier",
        7.7,
        "https://image.tmdb.org/t/p/w300/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg",
        50.182,
        "Action Adventure Sci-Fi",
        136,
        "After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.",
    ),
]
